Fixed bug in test_any where diff() results were used as an exit status.

diff --git a/phase1/test_any b/phase1/test_any
--- a/phase1/test_any
+++ b/phase1/test_any
@@ -38,13 +38,13 @@ fi
 # Compare
 DIFF=$(diff results/$TEST_NAME.res.out answers/$TEST_NAME.cor.out)
 
-if [ "$?" != "0" ]
-  then
-    echo "[ERROR] Problem comparing results."
-    exit 2
-  else
-    echo "[INFO] Comparison successful."
-fi
+#if [ "$?" != "0" ]
+#  then
+#    echo "[ERROR] Problem comparing results."
+#    exit 2
+#  else
+#    echo "[INFO] Comparison successful."
+#fi
 
 if [ "$DIFF" == "" ]
   then
